libpulsedsp		purge
pulseaudio		purge
rtkit		purge
liborc-0.4-0		purge
libogg0		purge
libwrap0		purge
udev		purge
python-notify		purge
libpulse0		purge
libvorbisenc2		purge
libjack-jackd2-0		purge
libsndfile1		purge
libasyncns0		purge
libspeexdsp1		purge
libtdb1		purge
libnss-systemd		purge
libasound2-plugins		purge
libflac8		purge
libvorbis0a		purge
pulseaudio-utils		purge
libnotify4		purge
libsamplerate0		purge
libwebrtc-audio-processing1		purge
